language: elixir

elixir:
  - 1.7.4
  - 1.8.1

otp_release:
  - 20.3

script:
  - mix coveralls.safe_travis
  - mix dialyzer --halt-exit-status
  - mix credo --strict

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
