language: elixir

elixir:
  - 1.7.4
  - 1.8.1

otp_release:
  - 20.3
before_script:
  - mix format --check-formatted

script:
  - mix coveralls.safe_travis
  - mix credo --strict

after_script:
  - MIX_ENV=test mix inch.report
